"""Package the built plugin with libfaust and the Faust libraries, for users without Faust.

    python plugin/package.py --build plugin/build --faust <Faust root> --out dist [--faust-version X.Y.Z] [--name <zip name>]

The Faust root is a Faust release laid out as lib/ (libfaust), share/faust/ (the .lib files)
and, optionally, a license file. Build the plugin with -DAUTOREAPER_PACKAGE=ON first, so it
finds libfaust beside itself. The result is a zip holding, per system:

    Windows  AutoReaper Faust/  AutoReaper Faust.clap, faust.dll, faustlibraries/
    Linux    AutoReaper Faust/  AutoReaper Faust.clap, libfaust.so.N, faustlibraries/
    macOS    AutoReaper Faust.clap  (a bundle: Contents/Frameworks/libfaust.2.dylib,
                                     Contents/Resources/faustlibraries and the notes; signed ad hoc)

Each lands in the folder where REAPER looks for CLAP plugins; see plugin/README.md.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

NAME = 'AutoReaper Faust'
REPOSITORY = Path(__file__).resolve().parents[1]

INSTALL = '''AutoReaper Faust {version}: a CLAP plugin that runs Faust code, with Faust {faust} included.

Install: copy {item} to the folder where REAPER finds CLAP plugins:
  Windows  %LOCALAPPDATA%\\Programs\\Common\\CLAP  (or C:\\Program Files\\Common Files\\CLAP)
  macOS    ~/Library/Audio/Plug-Ins/CLAP
  Linux    ~/.clap
then in REAPER: Options > Preferences > Plug-ins > CLAP > Re-scan.
{notes}
Licenses: AutoReaper is MIT (LICENSE). libfaust and the Faust libraries are by GRAME and contributors
under their own licenses (libfaust: LGPL-2.1 with an exception for generated code; see LICENSE-faust
and the headers of the .lib files). Source: https://github.com/grame-cncm/faust
'''

NOTES = {
    'win32': 'Needs the Microsoft Visual C++ Redistributable (x64), which most Windows computers have.\n',
    'darwin': ('The plugin is signed ad hoc, not notarized. If macOS blocks a downloaded copy, run:\n'
               '  xattr -dr com.apple.quarantine ~/Library/Audio/Plug-Ins/CLAP/"AutoReaper Faust.clap"\n'),
    'linux': '',
}


def run(*command):
    return subprocess.run(command, check=True, capture_output=True, text=True).stdout


def built_plugin(build):
    found = [p for p in build.rglob(f'{NAME}.clap') if 'CMakeFiles' not in p.parts]
    if not found:
        sys.exit(f'No "{NAME}.clap" under {build}: build the plugin first')
    return found[0]


def faust_libraries(faust, destination):
    source = faust / 'share' / 'faust'
    libraries = sorted(source.glob('*.lib'))
    if not any(lib.name == 'stdfaust.lib' for lib in libraries):
        sys.exit(f'No stdfaust.lib in {source}')
    destination.mkdir(parents=True)
    for lib in libraries:
        shutil.copy2(lib, destination / lib.name)


def faust_license(faust, destination):
    for name in ('COPYING.txt', 'COPYING', 'LICENSE', 'LICENSE.txt', 'COPYING.md'):
        for candidate in (faust / name, faust / 'share' / 'faust' / name, faust / 'share' / 'doc' / 'faust' / name):
            if candidate.is_file():
                shutil.copy2(candidate, destination / 'LICENSE-faust')
                return
    (destination / 'LICENSE-faust').write_text(
        'libfaust: GNU LGPL-2.1, with an exception for code generated by Faust.\n'
        'See https://github.com/grame-cncm/faust/blob/master-dev/COPYING.txt\n', encoding='utf-8')


def package_windows(build, faust, folder):
    folder.mkdir(parents=True)
    shutil.copy2(built_plugin(build), folder / f'{NAME}.clap')
    shutil.copy2(faust / 'lib' / 'faust.dll', folder / 'faust.dll')
    faust_libraries(faust, folder / 'faustlibraries')
    return folder


def package_linux(build, faust, folder):
    folder.mkdir(parents=True)
    plugin = folder / f'{NAME}.clap'
    shutil.copy2(built_plugin(build), plugin)
    library = next(p for p in sorted((faust / 'lib').glob('libfaust.so*')) if p.is_file() and not p.is_symlink())
    # The plugin asks for libfaust by the library's SONAME; the file must carry that name.
    soname = re.search(r'Library soname: \[([^\]]+)\]', run('readelf', '-d', str(library)))
    shutil.copy2(library, folder / (soname.group(1) if soname else library.name))
    faust_libraries(faust, folder / 'faustlibraries')
    missing = [line for line in run('ldd', str(plugin)).splitlines() if 'not found' in line]
    if missing:
        sys.exit('Unresolved libraries:\n' + '\n'.join(missing))
    return folder


def package_macos(build, faust, folder):
    folder.mkdir(parents=True)
    bundle = folder / f'{NAME}.clap'
    shutil.copytree(built_plugin(build), bundle, symlinks=True)
    binary = bundle / 'Contents' / 'MacOS' / NAME
    frameworks = bundle / 'Contents' / 'Frameworks'
    frameworks.mkdir()
    library = next(p for p in sorted((faust / 'lib').glob('libfaust.*.dylib')) if not p.is_symlink())
    # libfaust's install name is @rpath/libfaust.2.dylib; the plugin's rpath is ../Frameworks.
    install_name = re.search(r'^\s*(\S+libfaust[^\s]*)', run('otool', '-D', str(library)).splitlines()[-1])
    target = frameworks / Path(install_name.group(1)).name
    shutil.copy2(library, target)
    target.chmod(0o755)
    linked = run('otool', '-L', str(binary))
    if target.name not in linked:
        sys.exit(f'The plugin does not link {target.name}:\n{linked}')
    faust_libraries(faust, bundle / 'Contents' / 'Resources' / 'faustlibraries')
    return folder


def sign_macos(folder):
    """Copy the notes into the bundle, which install_faust_plugin installs alone, then sign it ad hoc."""
    bundle = folder / f'{NAME}.clap'
    for name in ('INSTALL.txt', 'LICENSE', 'LICENSE-faust'):
        shutil.copy2(folder / name, bundle / 'Contents' / 'Resources' / name)
    for library in (bundle / 'Contents' / 'Frameworks').iterdir():
        run('codesign', '--force', '--sign', '-', str(library))
    run('codesign', '--force', '--deep', '--sign', '-', str(bundle))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--build', type=Path, required=True)
    parser.add_argument('--faust', type=Path, required=True, help='Faust release root (lib/, share/faust/)')
    parser.add_argument('--out', type=Path, required=True)
    parser.add_argument('--faust-version', help='the Faust release, for INSTALL.txt (e.g. 2.88.0)')
    parser.add_argument('--name', help='zip file name without .zip (default: by system)')
    args = parser.parse_args()
    version = re.search(r'project\(\S+ VERSION (\S+)', (REPOSITORY / 'plugin' / 'CMakeLists.txt').read_text()).group(1)
    faust = args.faust_version or next((m.group(1) for p in (args.faust / 'lib').iterdir()
                                        if (m := re.fullmatch(r'libfaust\.(\d+\.\d+\.\d+)\.dylib', p.name))), '?')
    staging = args.out / 'staging'
    shutil.rmtree(staging, ignore_errors=True)
    folder = staging / NAME  # everything goes in here; the zip holds this folder
    if sys.platform == 'win32':
        package_windows(args.build, args.faust, folder)
        item, notes = f'the folder "{NAME}"', NOTES['win32']
    elif sys.platform == 'darwin':
        package_macos(args.build, args.faust, folder)
        item, notes = f'"{NAME}.clap" (from the folder "{NAME}")', NOTES['darwin']
    else:
        package_linux(args.build, args.faust, folder)
        item, notes = f'the folder "{NAME}"', NOTES['linux']
    (folder / 'INSTALL.txt').write_text(INSTALL.format(version=version, faust=faust,
                                                       item=item, notes=notes), encoding='utf-8')
    shutil.copy2(REPOSITORY / 'LICENSE', folder / 'LICENSE')
    faust_license(args.faust, folder)
    if sys.platform == 'darwin':
        sign_macos(folder)
    name = args.name or f'autoreaper-faust-{version}-{sys.platform}'
    archive = args.out / f'{name}.zip'
    archive.unlink(missing_ok=True)
    if sys.platform == 'darwin':
        # ditto keeps the bundle's symlinks, permissions and signature.
        run('ditto', '-c', '-k', '--keepParent', str(folder), str(archive))
    else:
        with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for path in sorted(folder.rglob('*')):
                zip_file.write(path, path.relative_to(staging))
    print(archive)


if __name__ == '__main__':
    main()
