-- Faust effects: the Faust code lives in a JSFX file the user edits in REAPER
-- (FX window > Edit...). Saving it compiles the code with the Faust compiler
-- into an include beside it, which the effect imports. The bridge loads this
-- file to compile on save; the server prepends it to its Faust requests.
--
--   Effects/AutoReaper/Faust/<slug>.jsfx            Faust code + generated pins/sliders + import
--   Effects/AutoReaper/Faust/<slug>.faust.jsfx-inc  JSFX code from Faust + status panel
--   Data/AutoReaper/Faust/<slug>.txt                build, ok|error, source hash, messages
--
-- A JSFX reloads only when it is recompiled. Its editor recompiles on save,
-- before the Faust build is ready, and taking the FX offline and online again
-- closes the editor. So an instance whose window is open is not reloaded: its
-- status panel asks for "Full recompile/reset" instead.
local faust = {}
local sep = package.config:sub(1, 1)
local START, FINISH = '/*FAUST', 'FAUST*/'
local GENERATED = '// Generated by AutoReaper from the Faust code above; do not edit below this line.'
faust.FOLDER = 'AutoReaper/Faust'

local function join(...) return table.concat({...}, sep) end

function faust.effects_dir() return join(reaper.GetResourcePath(), 'Effects', 'AutoReaper', 'Faust') end
function faust.data_dir() return join(reaper.GetResourcePath(), 'Data', 'AutoReaper', 'Faust') end

function faust.slug(name)
  local slug = tostring(name or ''):lower():gsub('[^%w]+', '_'):gsub('^_+', ''):gsub('_+$', '')
  assert(slug ~= '', 'name is required: a short name for the effect, e.g. "Lead Ducker"')
  return slug:sub(1, 60)
end

function faust.paths(slug)
  return {main = join(faust.effects_dir(), slug .. '.jsfx'), include = join(faust.effects_dir(), slug .. '.faust.jsfx-inc'),
          status = join(faust.data_dir(), slug .. '.txt'), ident = faust.FOLDER .. '/' .. slug .. '.jsfx',
          include_name = slug .. '.faust.jsfx-inc'}
end

function faust.read(path)
  local f = io.open(path, 'rb')
  if not f then return nil end
  local text = f:read('a'); f:close()
  return text
end

local function write(path, text)
  local f = assert(io.open(path .. '.tmp', 'wb')); f:write(text); f:close()
  os.remove(path); assert(os.rename(path .. '.tmp', path))
end

-- FNV-1a, 32 bit: tells whether the code changed since the last build.
function faust.hash(text)
  local h = 2166136261
  for i = 1, #text do h = ((h ~ text:byte(i)) * 16777619) & 0xffffffff end
  return string.format('%08x', h)
end

local function lines(text)
  local rows = {}
  for line in (text:gsub('\r\n', '\n') .. '\n'):gmatch('(.-)\n') do rows[#rows + 1] = line end
  if rows[#rows] == '' then rows[#rows] = nil end
  return rows
end

-- The Faust code of a main file: source, line number of its first line, the
-- text up to and including the start marker, and the text after the end marker.
function faust.split(text)
  local rows = lines(text)
  local first, last
  for i, line in ipairs(rows) do
    if not first and line:match('^%s*/%*FAUST%s*$') then first = i
    elseif first and line:match('^%s*FAUST%*/%s*$') then last = i; break end
  end
  if not (first and last) then return nil end
  return {source = table.concat(rows, '\n', first + 1, last - 1), line = first + 1,
          head = table.concat(rows, '\n', 1, first), tail = table.concat(rows, '\n', last + 1)}
end

function faust.check_source(source)
  assert(type(source) == 'string' and source:find('%S'), 'code is required: Faust code with a process definition')
  assert(not source:find('*/', 1, true), 'The code sits in a JSFX comment block, so it cannot contain "*/": use // comments')
end

function faust.template(name, source)
  local title = tostring(name):gsub('[%c]', ' ')
  return table.concat({
    'desc:' .. title .. ' (Faust)',
    '// Faust code (https://faustdoc.grame.fr/manual/syntax). Edit it below and save with Ctrl+S:',
    '// AutoReaper compiles it and shows the result in the FX window. Keep the code between',
    '// the FAUST markers and use // comments inside it.',
    START, source, FINISH, ''}, '\n')
end

-- The Faust compiler: AutoReaper's saved path (the server writes it), then the
-- usual install locations, then PATH.
function faust.compiler(mailbox)
  local saved = mailbox and faust.read(join(mailbox, 'faust-path.txt'))
  saved = saved and saved:match('^%s*(.-)%s*$')
  if saved and saved ~= '' and reaper.file_exists(saved) then return saved end
  for _, path in ipairs({'/opt/homebrew/bin/faust', '/usr/local/bin/faust', '/usr/bin/faust',
                         'C:\\Program Files\\Faust\\bin\\faust.exe'}) do
    if reaper.file_exists(path) then return path end
  end
  return 'faust'
end

local function quote(path) return '"' .. path .. '"' end

-- Faust messages with the build file's name replaced by line numbers of the
-- code as the reader sees it (offset = line number of the code's first line).
local function messages(output, dsp, offset)
  local rows = {}
  for _, line in ipairs(lines(output or '')) do
    if line:find('%S') then
      local at, rest = line:find(dsp, 1, true)
      if at then
        line = line:sub(1, at - 1) .. line:sub(rest + 1)
        line = line:gsub('^%s*:%s*(%d+)%s*:', function(n) return 'line ' .. (tonumber(n) + offset - 1) .. ':' end, 1)
      end
      rows[#rows + 1] = line
    end
  end
  return rows
end

-- Faust's JSFX output split into header lines (pins, sliders, options) and code.
-- Slider names lose Faust's "hslider_" prefix and "0" suffix; pins are numbered.
function faust.parse_jsfx(text)
  local header, body, inputs, outputs, controls, in_code = {}, {}, 0, 0, {}, false
  for _, line in ipairs(lines(text)) do
    if not in_code and line:match('^@') then in_code = true end
    if in_code then
      body[#body + 1] = line
    elseif line:match('^slider%d+:') then
      local before, label = line:match('^(slider%d+:[^>]*>)%a+_(.-)%s*$')
      if label then
        label = label:gsub('0$', '')
        line = before .. label
      end
      controls[#controls + 1] = line:match('>(.*)$')
      header[#header + 1] = line
    elseif line:match('^in_pin:') then
      inputs = inputs + 1; header[#header + 1] = 'in_pin:In ' .. inputs
    elseif line:match('^out_pin:') then
      outputs = outputs + 1; header[#header + 1] = 'out_pin:Out ' .. outputs
    elseif line:match('^options:') then
      header[#header + 1] = line
    end
  end
  return {header = header, body = table.concat(body, '\n'), inputs = inputs, outputs = outputs, controls = controls}
end

-- Compile Faust code to JSFX. Returns the parsed output, or nil and the messages.
function faust.compile(source, opts)
  local build_dir = assert(opts.build_dir, 'build_dir is required')
  reaper.RecursiveCreateDirectory(build_dir, 0)
  local dsp = join(build_dir, opts.slug .. '.dsp')
  local out = join(build_dir, opts.slug .. '.jsfx-out')
  write(dsp, source .. '\n')
  os.remove(out)
  local compiler = opts.compiler or 'faust'
  local command = table.concat({quote(compiler), '-lang', 'jsfx', '-I', quote(faust.effects_dir()), '-o', quote(out), quote(dsp)}, ' ')
  local result = reaper.ExecProcess(command, opts.timeout or 60000)
  local code, output = (result or ''):match('^(%-?%d+)\n?(.*)$')
  local notes = messages(output, dsp, opts.line or 1)
  if not result or tonumber(code) ~= 0 or not reaper.file_exists(out) then
    if not result or (tonumber(code) ~= 0 and #notes == 0) then
      notes[#notes + 1] = 'Could not run the Faust compiler (' .. compiler .. '). Install Faust ' ..
        '(https://github.com/grame-cncm/faust/releases, brew install faust, or apt install faust).'
    elseif output:lower():find('jsfx') and output:lower():find('unknown') then
      notes[#notes + 1] = 'This Faust has no JSFX backend; install a newer Faust.'
    end
    return nil, notes
  end
  local parsed = faust.parse_jsfx(assert(faust.read(out)))
  parsed.messages = notes
  return parsed
end

local function status_of(paths)
  local text = faust.read(paths.status)
  if not text then return nil end
  local rows = lines(text)
  return {build = tonumber(rows[1]) or 0, state = rows[2], hash = rows[3], messages = {table.unpack(rows, 4)}}
end
faust.status = status_of

local function include_build(paths)
  local text = faust.read(paths.include) or ''
  return tonumber(text:match('^// AutoReaper Faust build (%d+)')) or 0
end

local function write_status(paths, build, state, hash, notes)
  reaper.RecursiveCreateDirectory(faust.data_dir(), 0)
  local rows = {tostring(build), state, hash}
  for i = 1, math.min(#notes, 12) do rows[#rows + 1] = notes[i]:sub(1, 160) end
  write(paths.status, table.concat(rows, '\n') .. '\n')
end

-- The status panel: reads the status file twice a second and says whether the
-- loaded build is current, a newer one is waiting, or the code has errors.
local function panel(slug, build)
  return ([[
@gfx 600 120
autoreaper_now = time_precise();
autoreaper_now > autoreaper_next ? (
  autoreaper_next = autoreaper_now + 0.5;
  autoreaper_lines = 0; autoreaper_status_build = 0; strcpy(#autoreaper_state, "");
  autoreaper_file = file_open("AutoReaper/Faust/%s.txt");
  autoreaper_file >= 0 ? (
    file_string(autoreaper_file, #autoreaper_line); match("%%d", #autoreaper_line, autoreaper_status_build);
    file_string(autoreaper_file, #autoreaper_state);
    file_string(autoreaper_file, #autoreaper_line);
    while (autoreaper_lines < 12 && file_avail(autoreaper_file) != 0) (
      file_string(autoreaper_file, 900 + autoreaper_lines);
      strlen(900 + autoreaper_lines) > 0 ? autoreaper_lines += 1;
    );
    file_close(autoreaper_file);
  );
);
gfx_set(0.12, 0.12, 0.12); gfx_rect(0, 0, gfx_w, gfx_h);
gfx_x = 8; gfx_y = 6;
match("ok*", #autoreaper_state) ? (
  autoreaper_status_build > %d ? (
    gfx_set(1, 0.8, 0.3); gfx_drawstr("Faust: a new build is ready. In the editor (Edit...) click Full recompile/reset to load it.");
  ) : (
    gfx_set(0.5, 0.9, 0.5); gfx_drawstr("Faust: build %d loaded. Edit... shows the code; Ctrl+S compiles it.");
  );
) : match("error*", #autoreaper_state) ? (
  gfx_set(1, 0.45, 0.4); gfx_drawstr("Faust error; the effect still runs build %d. Line numbers are as in Edit...:");
) : (
  gfx_set(0.7, 0.7, 0.7); gfx_drawstr("Faust: no status yet.");
);
autoreaper_i = 0;
gfx_set(0.85, 0.85, 0.85);
while (autoreaper_i < autoreaper_lines) (
  gfx_x = 8; gfx_y += gfx_texth + 3; gfx_drawstr(900 + autoreaper_i); autoreaper_i += 1;
);
]]):format(slug, build, build, build)
end

local function include_text(slug, build, hash, body)
  local init = '@init\nautoreaper_build = ' .. build .. ';'
  local code, replaced = body:gsub('^@init[^\n]*', init, 1)
  if replaced == 0 then code = init .. '\n' .. body end
  return '// AutoReaper Faust build ' .. build .. ' of ' .. slug .. '.jsfx, source ' .. hash ..
    '. Generated from that file: edit the Faust code there.\n' .. code .. '\n' .. panel(slug, build)
end

-- Compile one effect and write its files. opts: slug, name (new effects),
-- source (nil: the code in the main file), compiler, build_dir, line_base
-- ('file' numbers lines as in the editor, 'code' from the code's first line),
-- keep_on_error (do not touch any file when the code does not compile).
function faust.build(opts)
  local paths = faust.paths(opts.slug)
  reaper.RecursiveCreateDirectory(faust.effects_dir(), 0)
  local existing = faust.read(paths.main)
  local parts = existing and faust.split(existing)
  if existing and not parts then
    error(paths.main .. ' has no ' .. START .. ' ... ' .. FINISH .. ' block; restore the markers around the Faust code', 0)
  end
  local source = opts.source or (parts and parts.source)
  assert(source, 'No effect named ' .. opts.slug .. ' yet: pass code to create it')
  faust.check_source(source)
  local head = parts and parts.head or faust.template(opts.name or opts.slug, ''):match('^(.-' .. START:gsub('%p', '%%%0') .. ')')
  local first_line = select(2, head:gsub('\n', '')) + 2
  local hash = faust.hash(source)
  local previous = include_build(paths)
  local result, notes = faust.compile(source, {slug = opts.slug, compiler = opts.compiler, build_dir = opts.build_dir,
                                               line = opts.line_base == 'code' and 1 or first_line})
  local report = {name = opts.slug, file = paths.main, include = paths.include, fx_name = 'JS:' .. paths.ident,
                  source_hash = hash}
  if not result then
    if not opts.keep_on_error then write_status(paths, previous, 'error', hash, notes) end
    report.ok, report.errors, report.running_build = false, notes, previous > 0 and previous or nil
    return report
  end
  if opts.source and parts and parts.source ~= opts.source then
    -- Ctrl+Z does not undo file changes: keep the code this build replaces.
    local history = join(opts.build_dir, 'history')
    reaper.RecursiveCreateDirectory(history, 0)
    report.previous_code = join(history, opts.slug .. '-' .. os.date('%Y%m%d-%H%M%S') .. '.dsp')
    write(report.previous_code, parts.source .. '\n')
  end
  local build = previous + 1
  local generated = {GENERATED}
  for _, line in ipairs(result.header) do generated[#generated + 1] = line end
  generated[#generated + 1] = 'import ' .. paths.include_name
  local main = head .. '\n' .. source .. '\n' .. FINISH .. '\n' .. table.concat(generated, '\n') .. '\n'
  write(paths.include, include_text(opts.slug, build, hash, result.body))
  report.main_rewritten = main ~= existing
  if report.main_rewritten then write(paths.main, main) end
  write_status(paths, build, 'ok', hash, {result.inputs .. ' in / ' .. result.outputs .. ' out' ..
    (#result.controls > 0 and (', controls: ' .. table.concat(result.controls, '; ')) or ''), table.unpack(result.messages)})
  report.ok, report.build, report.inputs, report.outputs = true, build, result.inputs, result.outputs
  report.controls, report.warnings = result.controls, result.messages
  return report
end

-- Instances of an effect in the active project (master and track FX chains).
function faust.instances(slug)
  local ident = faust.paths(slug).ident:lower()
  local rows = {}
  local function scan(track, track_name)
    for i = 0, reaper.TrackFX_GetCount(track) - 1 do
      local ok, id = reaper.TrackFX_GetNamedConfigParm(track, i, 'fx_ident')
      id = ok and id:gsub('\\', '/'):lower() or ''
      if id == ident or id:sub(-#ident - 1) == '/' .. ident then
        rows[#rows + 1] = {track = track, track_name = track_name, index = i}
      end
    end
  end
  scan(reaper.GetMasterTrack(0), 'MASTER')
  for t = 0, reaper.CountTracks(0) - 1 do
    local track = reaper.GetTrack(0, t)
    local _, name = reaper.GetTrackName(track)
    scan(track, name)
  end
  return rows
end

function faust.window_open(track, index)
  return reaper.TrackFX_GetFloatingWindow(track, index) ~= nil or reaper.TrackFX_GetChainVisible(track) == index
end

-- Taking a JSFX offline and online again recompiles it from its files.
function faust.reload(track, index)
  if reaper.TrackFX_GetOffline(track, index) then return false end
  reaper.TrackFX_SetOffline(track, index, true)
  reaper.TrackFX_SetOffline(track, index, false)
  return true
end

-- Called by the bridge about once a second: compile effects whose code changed
-- and reload instances whose window is closed (open ones show a hint).
function faust.watch(state)
  local dir = faust.effects_dir()
  state.pending = state.pending or {}
  for i = 0, 9999 do
    local file = reaper.EnumerateFiles(dir, i)
    if not file then break end
    local slug = file:match('^(.+)%.jsfx$')
    if slug then
      local paths = faust.paths(slug)
      local parts = faust.split(faust.read(paths.main) or '')
      local status = status_of(paths)
      if parts and parts.source:find('%S') and (not status or status.hash ~= faust.hash(parts.source)
          or not reaper.file_exists(paths.include)) then
        local ok, report = pcall(faust.build, {slug = slug, compiler = faust.compiler(state.mailbox),
                                               build_dir = state.build_dir, line_base = 'file'})
        if ok and report.ok then state.pending[slug] = true end
        if not ok then state.report('faust ' .. slug .. ': ' .. tostring(report)) end
      end
    end
  end
  for slug in pairs(state.pending) do
    local waiting = false
    for _, row in ipairs(faust.instances(slug)) do
      if faust.window_open(row.track, row.index) then waiting = true else faust.reload(row.track, row.index) end
    end
    if not waiting then state.pending[slug] = nil end
  end
end

return faust
